In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [6]:
arr2=np.arange(10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
arr_zeros=np.zeros((3,4))
arr_ones=np.ones((4,4))
print(arr_zeros)
print(arr_ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
arr3=np.array([1,2,3,4, 5])
print(arr3)
print(np.sqrt(3))
print(np.exp(arr3))

[1 2 3 4 5]
1.7320508075688772
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
